version: '2'
services:
    cakeclub-app:
        image: cakeclub
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cakeclub-postgresql:5432/cakeClub
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cakeclub-postgresql:
        extends:
            file: postgresql.yml
            service: cakeclub-postgresql
